#!/usr/bin/env bash

rsz()
{
    local DIR
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

    for arg in "$@"; do
        if [[ "$arg" == '--help' ]]; then
            source "$DIR/lib/print_help.bash"
            print_help
            exit 0
        fi
    done

    source "$DIR/argparse/single.bash"
    source "$DIR/argparse/double.bash"

    case "$#" in
        0)
            printf '1 to 2 arguments expected but got %d\n' "$#" >&2
            exit 1
        ;;
        1)
            argparse_single "$1"
        ;;
        2)
            argparse_double "$@"
        ;;
        *)
            source "$DIR/util/join_by.bash"
            printf '1 to 2 arguments expected but got %d: ["%s"]\n' "$#" "$(join_by '", "' "$@")" >&2
            exit 1
        ;;
    esac
    exit 0
}

rsz "$@"
