#!/usr/bin/env bash

source './argparse/single.bash'
source './argparse/double.bash'

rsz()
{
    case "$#" in
        1)
            argparse_single "$1"
            ;;
        2)
            argparse_double "$@"
            ;;
        *)
            printf 'Illegal number of arguments. 1 to 2 arguments expected but got %d: "%s"\n' "$#" "$*"
            exit 1
            ;;
    esac
    exit 0
}

rsz "$@"
