#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DIR/argparse/single.bash"
source "$DIR/argparse/double.bash"

rsz()
{
    case "$#" in
        1)
            argparse_single "$1"
            ;;
        2)
            argparse_double "$@"
            ;;
        *)
            printf '1 to 2 arguments expected but got %d: "%s"\n' "$#" "$*"
            exit 1
            ;;
    esac
    exit 0
}

rsz "$@"
